// <auto-generated />
using System;
using BookTicket.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookTicket.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191117065911_Tickets")]
    partial class Tickets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookTicket.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BookTicket.Models.Movies", b =>
                {
                    b.Property<int>("MoviesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("CategoryName");

                    b.Property<string>("FilmDate");

                    b.Property<string>("Image");

                    b.Property<bool>("IsApproved");

                    b.Property<bool>("IsSliderHome");

                    b.Property<bool>("IsSliderLogin1");

                    b.Property<bool>("IsSliderLogin2");

                    b.Property<string>("MoviesDescription");

                    b.Property<string>("MoviesDirector");

                    b.Property<string>("MoviesName");

                    b.Property<string>("MoviesSeans");

                    b.Property<int?>("TicketBiletNumberId");

                    b.HasKey("MoviesId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TicketBiletNumberId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("BookTicket.Models.Ticket", b =>
                {
                    b.Property<int>("BiletNumberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("FullorEmpty");

                    b.HasKey("BiletNumberId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BookTicket.Models.Movies", b =>
                {
                    b.HasOne("BookTicket.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookTicket.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketBiletNumberId");
                });
#pragma warning restore 612, 618
        }
    }
}
